"use client";
import Link from "next/link";
import { Suspense, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ExerciseCard } from "@/components/ExerciseCard";
import { SessionHeader } from "@/components/SessionHeader";
import { grammarWordExercises, grammarWords } from "@/data/grammar-words";
import { shuffleExercises } from "@/lib/practice-session";
import { useProgress } from "@/lib/progress";
import { Exercise, GrammarWord } from "@/types";

function GrammarWordDeck() {
  const search = useSearchParams(), { progress, setContinuation } = useProgress();
  const level = search.get("level") || "All", category = search.get("category") || "All", requestedId = search.get("id");
  const source = useMemo(() => grammarWords.filter(word => (level === "All" || word.level === level) && (category === "All" || word.category === category) && (!requestedId || word.id === requestedId)), [category, level, requestedId]);
  const [deck, setDeck] = useState<GrammarWord[]>(() => shuffleExercises(source)), [index, setIndex] = useState(0), [practice, setPractice] = useState<Exercise[]>([]), [practiceIndex, setPracticeIndex] = useState(0), [count, setCount] = useState(20);
  const touchStart = useRef<number | null>(null), word = deck[index];
  const move = useCallback((step: number) => { const next = Math.max(0, Math.min(deck.length - 1, index + step)), target = deck[next]; setIndex(next); if (target) setContinuation({ type: "grammar-words", label: `Grammar Words · ${target.category}`, href: `/grammar-words/study?id=${target.id}`, level: target.level, category: target.category, contentId: target.id, updatedAt: new Date().toISOString() }); }, [deck, index, setContinuation]);
  useEffect(() => { const key = (event: KeyboardEvent) => { if (["INPUT", "TEXTAREA", "SELECT"].includes((event.target as HTMLElement).tagName) || practice.length) return; if (event.key === "ArrowRight") move(1); if (event.key === "ArrowLeft") move(-1); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [move, practice.length]);
  const pool = useMemo(() => grammarWordExercises.filter(exercise => deck.some(item => exercise.id.startsWith(`gw-${item.id}-`))), [deck]);
  const startPractice = (single = false) => { const selected = single && word ? grammarWordExercises.filter(item => item.id.startsWith(`gw-${word.id}-`)) : pool; setPractice(shuffleExercises(selected).slice(0, single ? 4 : count)); setPracticeIndex(0); };
  if (!word) return <div className="page"><div className="card review-empty"><h1>No grammar words found</h1><Link className="button primary" href="/grammar-words">Change filters</Link></div></div>;
  if (practice[practiceIndex]) return <div className="page focused-session"><SessionHeader title={`${word.category} Practice`} current={practiceIndex + 1} total={practice.length} exitHref="/grammar-words" hasProgress={practiceIndex > 0}/><ExerciseCard exercise={practice[practiceIndex]} onDone={() => practiceIndex + 1 < practice.length ? setPracticeIndex(value => value + 1) : setPractice([])}/></div>;
  const stats = progress.grammarWordStats?.[word.id], related = word.relatedItems.map(id => grammarWords.find(item => item.id === id)).filter(Boolean) as GrammarWord[];
  const nav = <div className="flashcard-navigation"><button className="secondary" disabled={index === 0} onClick={() => move(-1)}>← Previous</button><button className="secondary" disabled={index === deck.length - 1} onClick={() => move(1)}>Next →</button></div>;
  return <div className="page vocab-study-page grammar-word-study" onTouchStart={event => { touchStart.current = event.changedTouches[0].clientX; }} onTouchEnd={event => { if (touchStart.current === null) return; const delta = event.changedTouches[0].clientX - touchStart.current; if (Math.abs(delta) > 55) move(delta < 0 ? 1 : -1); touchStart.current = null; }}><SessionHeader title="Grammar Words" current={index + 1} total={deck.length} exitHref="/grammar-words" hasProgress={!!stats?.attempts}/><div className="study-toolbar"><Link href="/grammar-words" className="back-link">Deck settings</Link><div className="study-selects"><span>Practice:</span>{[10,20,30].map(value => <button className={count === value ? "primary" : "secondary"} key={value} onClick={() => setCount(value)}>{value}</button>)}<button className="secondary" onClick={() => { setDeck(shuffleExercises(deck)); setIndex(0); }}>Shuffle Again</button><button className="primary" onClick={() => startPractice()}>Start {Math.min(count, pool.length)} Questions</button></div></div><div className="flashcard-navigation-top">{nav}</div><article className="vocab-flashcard grammar-word-card"><div className="pills"><span className="pill">{word.level}</span><span className="pill">{word.category}</span>{word.case && <span className="pill">{word.case}</span>}</div><div className="flashcard-front"><h1>{word.german}</h1><p className="flashcard-english"><small>English</small>{word.englishMeaning}</p><p className="flashcard-turkish"><small>Türkçe</small>{word.turkishMeaning}</p></div><div className="grammar-rule"><small>How it works</small><strong>{word.shortExplanationEnglish}</strong><p>{word.sentenceRule}</p></div><div className="flashcard-examples">{word.examples.map(example => <div className="flashcard-example" key={`${example.context}-${example.german}`}><small>{example.context === "it" ? "IT example" : "Daily example"}</small><strong>{example.german}</strong><span><b>English:</b> {example.english}</span></div>)}</div>{stats && <p className="grammar-word-stat">Practiced {stats.attempts} times · {Math.round(stats.correct / stats.attempts * 100)}% correct</p>}</article><div className="related-word-links">{related.map(item => <Link className="pill" href={`/grammar-words/study?id=${item.id}`} key={item.id}>{item.german}</Link>)}</div><div className="flashcard-navigation"><button className="secondary" disabled={index === 0} onClick={() => move(-1)}>← Previous</button><button className="primary" onClick={() => startPractice(true)}>Practice This Word</button><button className="secondary" disabled={index === deck.length - 1} onClick={() => move(1)}>Next →</button></div></div>;
}
export default function GrammarWordStudyPage() { return <Suspense fallback={<div className="page"><div className="card">Building your deck…</div></div>}><GrammarWordDeck/></Suspense>; }
