"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { REPORT_ADMIN_UID } from "@/lib/firebase/paths";
import { useAuth } from "@/lib/auth";
type ListedUser={uid:string;email:string;displayName:string};
type Day={date:string;firstActivityAt?:string|null;lastActivityAt?:string|null;activeStudySeconds?:number;questionsAnswered?:number;cardsStudied?:number;reviewItemsCompleted?:number;correctAnswers?:number;incorrectAnswers?:number};
const turkeyDate=(offset=0)=>{const base=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),date=new Date(`${base}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+offset);return date.toISOString().slice(0,10)};
const duration=(seconds=0)=>seconds>=3600?`${Math.floor(seconds/3600)}h ${Math.round(seconds%3600/60)}m`:`${Math.round(seconds/60)} min`;
const clock=(value?:string|null)=>value?new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Istanbul",hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"—";
export default function AdminReportsPage(){
 const {user}=useAuth(),router=useRouter(),[users,setUsers]=useState<ListedUser[]>([]),[uid,setUid]=useState(""),[from,setFrom]=useState(turkeyDate(-6)),[to,setTo]=useState(turkeyDate()),[days,setDays]=useState<Day[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 useEffect(()=>{if(user&&user.uid!==REPORT_ADMIN_UID)router.replace("/");},[router,user]);
 useEffect(()=>{if(user?.uid!==REPORT_ADMIN_UID)return;user.getIdToken().then(token=>fetch("/api/admin/users",{headers:{Authorization:`Bearer ${token}`}})).then(response=>response.ok?response.json():Promise.reject()).then(data=>{setUsers(data.users);if(data.users[0])setUid(data.users[0].uid)}).catch(()=>setError("User list is unavailable. Check Firebase Admin configuration."));},[user]);
 const load=async()=>{if(!user||!uid)return;setLoading(true);setError("");try{const token=await user.getIdToken();const response=await fetch(`/api/admin/reports?uid=${encodeURIComponent(uid)}&from=${from}&to=${to}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error();const data=await response.json();setDays(data.days);}catch{setError("The report could not be loaded.");}finally{setLoading(false)}};
 const totals=useMemo(()=>days.reduce((sum,day)=>({seconds:sum.seconds+(day.activeStudySeconds||0),questions:sum.questions+(day.questionsAnswered||0),cards:sum.cards+(day.cardsStudied||0),reviews:sum.reviews+(day.reviewItemsCompleted||0),correct:sum.correct+(day.correctAnswers||0),incorrect:sum.incorrect+(day.incorrectAnswers||0)}),{seconds:0,questions:0,cards:0,reviews:0,correct:0,incorrect:0}),[days]), today=days.find(day=>day.date===turkeyDate()), todayAnswers=(today?.correctAnswers||0)+(today?.incorrectAnswers||0), accuracy=todayAnswers?Math.round((today?.correctAnswers||0)/todayAnswers*100):0;
 const preset=(count:number)=>{setFrom(turkeyDate(-(count-1)));setTo(turkeyDate())};
 const exportCsv=async()=>{if(!user||!uid)return;const token=await user.getIdToken();const response=await fetch(`/api/admin/reports/export?uid=${encodeURIComponent(uid)}&from=${from}&to=${to}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok){setError("CSV export was denied or unavailable.");return;}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=response.headers.get("content-disposition")?.match(/filename="(.+)"/)?.[1]||"study-report.csv";link.click();URL.revokeObjectURL(url)};
 if(user?.uid!==REPORT_ADMIN_UID)return <div className="page"><div className="card review-empty">Checking authorization…</div></div>;
 return <div className="page app-page admin-reports"><div className="simple-heading"><div className="eyebrow">Admin only</div><h1>Study Reports</h1><p>Approximate learning activity in Europe/Istanbul time.</p></div><section className="card report-filters"><label>User<select value={uid} onChange={event=>setUid(event.target.value)}>{users.map(item=><option key={item.uid} value={item.uid}>{item.displayName?`${item.displayName} · `:""}{item.email||item.uid}</option>)}</select></label><div><label>Date range</label><div className="segmented"><button onClick={()=>preset(1)}>Today</button><button onClick={()=>preset(7)}>7 Days</button><button onClick={()=>preset(30)}>30 Days</button></div></div><label>From<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>To<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><button className="primary" disabled={!uid||loading} onClick={load}>{loading?"Loading…":"View Report"}</button><button className="secondary" disabled={!uid} onClick={exportCsv}>Export CSV</button></section>{error&&<div className="auth-message error">{error}</div>}<section className="report-today"><h2>Today</h2><div className="simple-numbers"><span><small>Active study time</small><strong>{duration(today?.activeStudySeconds)}</strong></span><span><small>First activity</small><strong>{clock(today?.firstActivityAt)}</strong></span><span><small>Last activity</small><strong>{clock(today?.lastActivityAt)}</strong></span><span><small>Questions</small><strong>{today?.questionsAnswered||0}</strong></span><span><small>Cards</small><strong>{today?.cardsStudied||0}</strong></span><span><small>Accuracy</small><strong>{accuracy}%</strong></span></div></section><section className="card"><div className="report-summary"><span><small>Total active time</small><strong>{duration(totals.seconds)}</strong></span><span><small>Daily average</small><strong>{duration(days.length?totals.seconds/days.length:0)}</strong></span><span><small>Review completed</small><strong>{totals.reviews}</strong></span></div><div className="report-days">{days.length?days.map(day=>{const total=(day.correctAnswers||0)+(day.incorrectAnswers||0);return <div key={day.date}><strong>{day.date}</strong><span>{duration(day.activeStudySeconds)}</span><span>{day.questionsAnswered||0} questions</span><span>{day.cardsStudied||0} cards</span><b>{total?Math.round((day.correctAnswers||0)/total*100):0}%</b></div>}):<p className="muted">No activity in this date range.</p>}</div></section></div>;
}
