import {readFile,writeFile,mkdir,mkdtemp,rm} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {PDFParse} from 'pdf-parse';
import type {Exercise,Level,VocabularyItem} from '../types';

const exec=promisify(execFile);const root=resolve(process.cwd());
const outputDir=join(root,'data/generated');const overridesPath=join(root,'data/overrides/goethe-overrides.json');
const dictionaryUrl='https://download.freedict.org/dictionaries/deu-eng/1.9-fd1/freedict-deu-eng-1.9-fd1.src.tar.xz';
type Imported=VocabularyItem&{source:'goethe';sourceType:'wordlist';externalKey:string;exampleSource?:'goethe';englishSource?:'freedict'|'override'};
type Override=Partial<Imported>&{skip?:boolean};type Report={level:Level;sourceEntriesDetected:number;validVocabularyEntries:number;duplicatesSkipped:number;entriesWithEnglishMeaning:number;entriesWithExamples:number;warnings:string[]};

const forbidden=/GOETHE|ZERTIFIKAT|WORTLISTE|INVeNTAre|Seite|ISBN|Wortschatz|Copyright|www\.|VS_0|START DEUTSCH/i;
const auxiliaries=/^(hat|hatte|ist|sind|war|waren|wurde|wurden|kann|können|muss|müssen|soll|sollen|wird|werden|zieht|gezogen|ging|kam|gab|fand|hätte|würde)\b/i;
const entity=(s:string)=>s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/<[^>]+>/g,'').trim();
const keyText=(s:string)=>s.toLocaleLowerCase('de-DE').normalize('NFC').replace(/^\((sich)\)\s*|^sich\s+/,'').replace(/[^a-zäöüß0-9]+/g,'-').replace(/^-|-$/g,'');
const stableKey=(level:Level,german:string,pos:string)=>`goethe:${level.toLowerCase()}:${keyText(german)}:${pos}`;
const stableId=(key:string)=>`goethe-${createHash('sha1').update(key).digest('hex').slice(0,16)}`;
function parts(raw:string){let s=raw.replace(/[‐‑–]/g,'-').replace(/\s+/g,' ').trim();let article:VocabularyItem['article'];const a=s.match(/^(der\/die|der|die|das)\s+/i);if(a){article=a[1].toLowerCase();s=s.slice(a[0].length)}s=s.replace(/^\(sich\)\s*/,'sich ');const comma=s.indexOf(',');const german=(comma>=0?s.slice(0,comma):s).trim().replace(/\s*→.*$/,'').replace(/[.!]$/,'');const plural=article&&comma>=0?s.slice(comma+1).trim().replace(/\s*→.*$/,'')||undefined:undefined;const pos=article?'noun':/^(sich\s+)?[a-zäöüß-]+(?:en|ern|eln)$/.test(german)?'verb':'other';return {german,article,plural,partOfSpeech:pos}}
function validHead(raw:string,level:Level){const s=raw.trim();if(!s||forbidden.test(s)||/^[-–—]|^\d|^[A-ZÄÖÜ]$/.test(s)||s.length>90||auxiliaries.test(s)||(/^\([^)]*\)(?!\s*sich)/.test(s)&&!/^\(sich\)/.test(s))||(/[.!?].+\s/.test(s)&&s!=='Achtung!'))return false;if(level!=='B1')return true;const p=parts(s);return !!p.article||/^\(?sich\)?\s/.test(s)||/^[a-zäöüß-]+(?:en|ern|eln)(?:,|$)/.test(s)||(/^[a-zäöüß-]+$/.test(s)&&s.length>2)}
function category(german:string){const g=keyText(german);const sets:[string,RegExp][]=[['Food',/apfel|brot|kaffee|essen|trinken|restaurant|käse|fleisch|banane|küche/],['Work',/arbeit|beruf|chef|kollege|firma|stelle|bewerb/],['Family',/famil|mutter|vater|eltern|bruder|schwester|kind/],['Transportation',/bahn|bus|zug|auto|fahr|reise|flug|verkehr|anschluss/],['Housing',/wohnung|haus|zimmer|miete|möbel|küche|bad/],['Health',/arzt|krank|gesund|apotheke|husten|schmerz|ausruh/],['Time',/uhr|zeit|tag|monat|jahr|termin/],['Communication',/telefon|anruf|brief|mail|antwort|frage|sprech/],['Administration',/amt|antrag|anmeldung|formular|ausweis|genehm/],['School',/schule|unterricht|lern|prüfung|aufgabe/],['Shopping',/kauf|preis|geld|rechnung|geschäft/]];return sets.find(([,r])=>r.test(g))?.[0]||'General'}
async function extractPdf(level:Level){const data=await readFile(join(root,`assets/wordlists/${level.toLowerCase()}_wordlist.pdf`));const parser=new PDFParse({data});const result=await parser.getText();await parser.destroy();return result.text.replace(/([A-Za-zÄÖÜäöüß])-\n([a-zäöüß])/g,'$1$2')}
function parseA(text:string,level:'A1'|'A2'){const start=level==='A1'?text.indexOf('\nA\nab '):text.indexOf('ALPHABETISCHER WORTSCHATZ');const body=text.slice(Math.max(0,start));const found:{head:string;example?:string}[]=[];for(const line of body.split('\n')){if(!line.includes('\t'))continue;const [head,...right]=line.split('\t').map(x=>x.trim()).filter(Boolean);if(!head||!validHead(head,level))continue;const example=right.join(' ').trim();found.push({head,example:/[.!?]$/.test(example)&&example.length>8?example:undefined})}return found}
function parseB1(text:string){const pages=text.split(/-- \d+ of \d+ --/).slice(16);const found:{head:string;example?:string}[]=[];for(const page of pages){const lines=page.split('\n').map(x=>x.trim()).filter(Boolean);let started=false;for(const line of lines){if(forbidden.test(line)||/^\d+\s+WORTLISTE$/.test(line)||/^\d+$/.test(line))continue;if(!started){if(validHead(line,'B1'))started=true;else continue}if(/^\d+\.|^[A-ZÄÖÜ].*[.!?]$/.test(line)&&!/^Achtung!?$/.test(line))break;if(validHead(line,'B1'))found.push({head:line})}}return found}
async function dictionary(){let tei=process.env.FREEDICT_TEI;let cleanup='';if(!tei){const dir=await mkdtemp(join(tmpdir(),'deutschwerk-freedict-'));cleanup=dir;const archive=join(dir,'dictionary.tar.xz');const response=await fetch(dictionaryUrl);if(!response.ok)throw new Error(`FreeDict download failed: ${response.status}`);await writeFile(archive,Buffer.from(await response.arrayBuffer()));await exec('tar',['-xf',archive,'-C',dir]);tei=join(dir,'deu-eng/deu-eng.tei')}const xml=await readFile(tei,'utf8');const map=new Map<string,string[]>();for(const match of xml.matchAll(/<entry\b[\s\S]*?<\/entry>/g)){const block=match[0];const orth=block.match(/<orth(?:\s[^>]*)?>([\s\S]*?)<\/orth>/)?.[1];if(!orth)continue;const translations=[...block.matchAll(/<cit type="trans">\s*<quote xml:lang="en">([\s\S]*?)<\/quote>/g)].map(x=>entity(x[1])).filter(x=>x&&!/[<>]/.test(x)&&x.length<70);if(translations.length){const key=keyText(entity(orth));map.set(key,[...new Set([...(map.get(key)||[]),...translations])])}}for(const [key,values] of map)map.set(key,values.sort((a,b)=>a.split(/\s+/).length-b.split(/\s+/).length||a.length-b.length).slice(0,4));if(cleanup)await rm(cleanup,{recursive:true,force:true});return map}
function makeExercises(items:Imported[]){const all:Exercise[]=[];for(const level of ['A1','A2','B1'] as Level[]){const usable=items.filter(x=>x.level===level&&x.englishMeaning).slice(0,40);for(const item of usable){const distractors=[...new Set(usable.filter(x=>x.id!==item.id&&x.englishMeaning!==item.englishMeaning).map(x=>x.englishMeaning))].slice(0,3);if(distractors.length<3)continue;all.push({id:`goethe-ex-${item.id}-meaning`,type:'vocabulary',level,category:item.category,prompt:`Was bedeutet „${item.article?`${item.article} `:''}${item.german}“ auf Englisch?`,englishHelp:'Choose the correct English meaning.',answer:item.englishMeaning,answerEnglish:item.englishMeaning,options:[item.englishMeaning,...distractors].sort(),explanation:`${item.german} = ${item.englishMeaning}`});if(item.exampleSentence&&item.exampleEnglishTranslation){const escaped=item.german.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const blank=item.exampleSentence.replace(new RegExp(escaped,'i'),'_____');if(blank!==item.exampleSentence)all.push({id:`goethe-ex-${item.id}-blank`,type:'fill_blank',level,category:item.category,prompt:blank,englishHelp:item.exampleEnglishTranslation,answer:item.german,answerEnglish:item.englishMeaning,explanation:`The missing word is “${item.german}”.`})}}}return all}
async function main(){await mkdir(outputDir,{recursive:true});const overrides=JSON.parse(await readFile(overridesPath,'utf8')) as Record<string,Override>;const dict=await dictionary();const reports:Report[]=[];const combined:Imported[]=[];for(const level of ['A1','A2','B1'] as Level[]){const text=await extractPdf(level);const detected=level==='B1'?parseB1(text):parseA(text,level);const seen=new Set<string>();const items:Imported[]=[];let duplicates=0;const warnings:string[]=[];for(const source of detected){const p=parts(source.head);if(!p.german||forbidden.test(p.german)||p.german.length<2){warnings.push(`Rejected malformed headword: ${source.head}`);continue}const key=stableKey(level,p.german,p.partOfSpeech);if(seen.has(key)){duplicates++;continue}seen.add(key);const override=overrides[key];if(override?.skip)continue;const meanings=dict.get(keyText(p.german));const item:Imported={id:stableId(key),...p,englishMeaning:meanings?.join(' / ')||'',level,category:category(p.german),source:'goethe',sourceType:'wordlist',externalKey:key,exampleSentence:source.example,exampleEnglishTranslation:undefined,tags:['goethe',level.toLowerCase()],englishSource:meanings?'freedict':undefined,exampleSource:source.example?'goethe':undefined,...override};items.push(item)}const missing=items.filter(x=>!x.englishMeaning).length;if(missing)warnings.push(`${missing} entries have no FreeDict or override English match.`);const report={level,sourceEntriesDetected:detected.length,validVocabularyEntries:items.length,duplicatesSkipped:duplicates,entriesWithEnglishMeaning:items.length-missing,entriesWithExamples:items.filter(x=>x.exampleSentence).length,warnings};reports.push(report);combined.push(...items);await writeFile(join(outputDir,`goethe-${level.toLowerCase()}.json`),JSON.stringify(items,null,2)+'\n')}await writeFile(join(outputDir,'goethe-exercises.json'),JSON.stringify(makeExercises(combined),null,2)+'\n');await writeFile(join(outputDir,'import-report.json'),JSON.stringify(reports,null,2)+'\n');const md=['# Goethe wordlist import report','',...reports.flatMap(r=>[`## ${r.level}`,`- Source entries detected: ${r.sourceEntriesDetected}`,`- Valid vocabulary entries: ${r.validVocabularyEntries}`,`- Duplicates skipped: ${r.duplicatesSkipped}`,`- Entries with English meaning: ${r.entriesWithEnglishMeaning}`,`- Entries with source examples: ${r.entriesWithExamples}`,`- Warnings: ${r.warnings.length}`,...r.warnings.map(w=>`  - ${w}`),''])].join('\n');await writeFile(join(outputDir,'import-report.md'),md);console.log(md)}
main().catch(error=>{console.error(error);process.exitCode=1});
